"""Add Position to User Table

Revision ID: 580682a4ab1d
Revises: c8d232b5dda7
Create Date: 2025-06-29 17:13:39.082625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '580682a4ab1d'
down_revision: Union[str, Sequence[str], None] = 'c8d232b5dda7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user', sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('position', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'position')
    # ### end Alembic commands ###
